"""initial schema

Revision ID: 4855b9c370d3
Revises: 
Create Date: 2026-03-01 17:34:42.377962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4855b9c370d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability',
    sa.Column('capability_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('owner_team', sa.String(), nullable=True),
    sa.Column('current_maturity', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('roadmap_status', sa.String(), nullable=False),
    sa.Column('known_gaps', sa.Text(), nullable=False),
    sa.Column('dependent_pm_ids', sa.Text(), nullable=False),
    sa.Column('linked_project_ids', sa.Text(), nullable=False),
    sa.Column('asana_gid', sa.String(), nullable=True),
    sa.Column('asana_synced_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('capability_id')
    )
    with op.batch_alter_table('capability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capability_asana_gid'), ['asana_gid'], unique=True)

    op.create_table('decision',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('options_considered', sa.Text(), nullable=True),
    sa.Column('chosen_path', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('approvers', sa.Text(), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('impacted_artifact_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_table('pm_coverage',
    sa.Column('pm_id', sa.String(), nullable=False),
    sa.Column('pm_name', sa.String(), nullable=False),
    sa.Column('team_or_pod', sa.String(), nullable=True),
    sa.Column('strategy_type', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('coverage_owner', sa.String(), nullable=True),
    sa.Column('onboarding_stage', sa.String(), nullable=False),
    sa.Column('go_live_target_date', sa.Date(), nullable=True),
    sa.Column('health_status', sa.String(), nullable=False),
    sa.Column('last_touchpoint_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_project_ids', sa.Text(), nullable=False),
    sa.Column('asana_gid', sa.String(), nullable=True),
    sa.Column('asana_synced_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('pm_id')
    )
    with op.batch_alter_table('pm_coverage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pm_coverage_asana_gid'), ['asana_gid'], unique=True)

    op.create_table('project',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=False),
    sa.Column('business_objective', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('health_status', sa.String(), nullable=False),
    sa.Column('primary_pm_ids', sa.Text(), nullable=False),
    sa.Column('linked_pm_need_ids', sa.Text(), nullable=False),
    sa.Column('linked_capability_ids', sa.Text(), nullable=False),
    sa.Column('asana_gid', sa.String(), nullable=True),
    sa.Column('asana_synced_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_asana_gid'), ['asana_gid'], unique=True)

    op.create_table('risk',
    sa.Column('risk_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('risk_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('date_opened', sa.Date(), nullable=False),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('escalation_status', sa.String(), nullable=False),
    sa.Column('impacted_pm_ids', sa.Text(), nullable=False),
    sa.Column('impacted_project_ids', sa.Text(), nullable=False),
    sa.Column('impacted_milestone_ids', sa.Text(), nullable=False),
    sa.Column('asana_gid', sa.String(), nullable=True),
    sa.Column('asana_synced_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('risk_id')
    )
    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_asana_gid'), ['asana_gid'], unique=True)

    op.create_table('milestone',
    sa.Column('milestone_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('gating_conditions', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('asana_gid', sa.String(), nullable=True),
    sa.Column('asana_synced_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('milestone_id')
    )
    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestone_asana_gid'), ['asana_gid'], unique=True)
        batch_op.create_index(batch_op.f('ix_milestone_project_id'), ['project_id'], unique=False)

    op.create_table('pm_need',
    sa.Column('need_id', sa.String(), nullable=False),
    sa.Column('pm_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('business_rationale', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('date_raised', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('business_impact', sa.String(), nullable=True),
    sa.Column('desired_by_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution_path', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_project_ids', sa.Text(), nullable=False),
    sa.Column('mapped_capability_id', sa.String(), nullable=True),
    sa.Column('asana_gid', sa.String(), nullable=True),
    sa.Column('asana_synced_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pm_id'], ['pm_coverage.pm_id'], ),
    sa.PrimaryKeyConstraint('need_id')
    )
    with op.batch_alter_table('pm_need', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pm_need_asana_gid'), ['asana_gid'], unique=True)
        batch_op.create_index(batch_op.f('ix_pm_need_pm_id'), ['pm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm_need', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pm_need_pm_id'))
        batch_op.drop_index(batch_op.f('ix_pm_need_asana_gid'))

    op.drop_table('pm_need')
    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestone_project_id'))
        batch_op.drop_index(batch_op.f('ix_milestone_asana_gid'))

    op.drop_table('milestone')
    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_asana_gid'))

    op.drop_table('risk')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_asana_gid'))

    op.drop_table('project')
    with op.batch_alter_table('pm_coverage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pm_coverage_asana_gid'))

    op.drop_table('pm_coverage')
    op.drop_table('decision')
    with op.batch_alter_table('capability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capability_asana_gid'))

    op.drop_table('capability')
    # ### end Alembic commands ###
