"""Status Update domain model.

Source of truth: Asana (project-level status updates use Asana's native feature).
Sidecar reads and stores status update metadata for rollup views.
"""

from datetime import datetime
from enum import StrEnum

from pydantic import Field

from .common import AsanaLinkedRecord, HealthStatus


class StatusScopeType(StrEnum):
    PROJECT = "project"
    PM = "pm"
    INITIATIVE = "initiative"


class StatusUpdate(AsanaLinkedRecord):
    """A concise structured snapshot for stakeholders.

    Project-level updates use Asana's native status update feature.
    PM-level and initiative-level rollups are generated by the sidecar.
    """

    status_update_id: str = Field(description="Internal sidecar identifier")
    scope_type: StatusScopeType
    scope_id: str = Field(description="ID of the PM, project, or initiative this covers")
    overall_status: HealthStatus = HealthStatus.UNKNOWN
    what_changed_this_period: str | None = None
    next_key_milestones: str | None = None
    top_blockers: str | None = None
    decisions_needed: str | None = None
    confidence: str | None = None
    updated_by: str | None = None
    updated_at: datetime | None = None
